hadd -f /nfs_scratch/laura/pipl_pt_10.root /hdfs/store/user/laura/06-09-PiPlus_Pt10-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_15.root /hdfs/store/user/laura/06-09-PiPlus_Pt15-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_20.root /hdfs/store/user/laura/06-09-PiPlus_Pt20-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_25.root /hdfs/store/user/laura/06-09-PiPlus_Pt25-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_30.root /hdfs/store/user/laura/06-09-PiPlus_Pt30-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_35.root /hdfs/store/user/laura/06-09-PiPlus_Pt35-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_40.root /hdfs/store/user/laura/06-09-PiPlus_Pt40-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_45.root /hdfs/store/user/laura/06-09-PiPlus_Pt45-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_50.root /hdfs/store/user/laura/06-09-PiPlus_Pt50-makePuMultTrees_cfg/*.root
hadd -f /nfs_scratch/laura/pipl_pt_55.root /hdfs/store/user/laura/06-09-PiPlus_Pt55-makePuMultTrees_cfg/*.root
