hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt10-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt15-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt20-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt25-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt30-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt35-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt40-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt45-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_50.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt50-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pipl_calib_v2_pt_55.root /hdfs/store/user/laura/07-01_v2_eg2_v1eg2-PiPlus_Pt55-makePionImplTrees_cfg/*.root
