hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_10.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt10-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_15.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt15-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_20.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt20-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_25.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt25-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_30.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt30-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_35.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt35-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_40.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt40-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_45.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt45-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_50.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt50-makePionImplTrees_cfg/*.root
hadd -f /cms/laura/pionSamples/pi0_calib_v1_pt_55.root /hdfs/store/user/laura/07-02_v1-Pi0_Pt55-makePionImplTrees_cfg/*.root
