python pi0_nocalib/TPG_SF.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_EvsH.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_ETPG.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_noise.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_EoTot.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_HTPG.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_HoE.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_HoTot.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_Tot.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_TotGen.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_Totmax.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_Totres.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_

python pi0_nocalib/TPG_TotSum.py /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_10.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_15.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_20.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_25.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_30.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_35.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_40.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_45.root /cms/laura/pionSamples/pi0_calib_v2_bugfix_pt_50.root July02TPG/pi0_
