python pipl/TPG_SF.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_EvsH.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_ETPG.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_EoTot.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_HTPG.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_HoE.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_HoTot.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_Tot.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_TotGen.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_Totmax.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_Totres.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

python pipl/TPG_TotSum.py /cms/laura/pionSamples/pipl_calib_v2_pt_10.root /cms/laura/pionSamples/pipl_calib_v2_pt_15.root /cms/laura/pionSamples/pipl_calib_v2_pt_20.root /cms/laura/pionSamples/pipl_calib_v2_pt_25.root /cms/laura/pionSamples/pipl_calib_v2_pt_30.root /cms/laura/pionSamples/pipl_calib_v2_pt_35.root /cms/laura/pionSamples/pipl_calib_v2_pt_40.root /cms/laura/pionSamples/pipl_calib_v2_pt_45.root /cms/laura/pionSamples/pipl_calib_v2_pt_50.root TPG_CALIB_EG_2/pipl

